export const BUCKET = `https://res.cloudinary.com/ddwjnjssj/image/upload/v1696748775`
export const BUCKET_PREFIX = `https://res.cloudinary.com/ddwjnjssj/image/upload/v1696748775`
export const BUCKET_IMAGE = `${BUCKET_PREFIX}/images`
export const BUCKET_IMAGE_CHAT = `${BUCKET_IMAGE}/chat-images`
export const BUCKET_IMAGE_POST = `${BUCKET_IMAGE}/posts-images`
export const BUCKET_IMAGE_POST_UPLOAD = `images/posts-images`
export const BUCKET_IMAGE_BANNER = `${BUCKET_IMAGE}/banners`
export const BUCKET_IMAGE_AVATAR = `${BUCKET_IMAGE}/avatar`
export const BUCKET_IMAGE_THEME = `${BUCKET_IMAGE}/themes`
export const BUCKET_IMAGE_APPLICATION = `${BUCKET_IMAGE}/applications`
export const BUCKET_IMAGE_COMPANY_ICON = `${BUCKET_IMAGE}/icons/company`
export const BUCKET_IMAGE_WELCOME = `${BUCKET_IMAGE}/welcome-images`
export const BUCKET_IMAGE_COMPANIES_LOGO = `${BUCKET_IMAGE}/companies-logo`
export const BUCKET_IMAGE_COMPANIES_LOGO_UPLOAD = `images/companies-logo`
export const BUCKET_IMAGE_DEFAULT = `${BUCKET_IMAGE}/default`
export const BUCKET_CV = `${BUCKET_PREFIX}/cv-bucket`
export const BUCKET_CV_UPLOAD = `cv-bucket`
export const BUCKET_IMAGE_PARENT = `images/category`
export const BUCKET_IMAGE_PARENT_DEFAULT = `images/default-post-image`    
export const BUCKET_IMAGE_COMMUNICATION = `${BUCKET_IMAGE}/communications`
export const BUCKET_IMAGE_COMMUNICATION_UPLOAD = `images/communications`
export const BUCKET_IMAGE_COMMUNICATION_COMMENT = `${BUCKET_IMAGE}/communications-comment`
export const BUCKET_IMAGE_COMMUNICATION_COMMENT_UPLOAD = `images/communications-comment`
export const BUCKET_IMAGE_CV_TEMPLATE = `${BUCKET_IMAGE}/cv-templates`
export const BUCKET_IMAGE_CV_INFORMATION= `${BUCKET_IMAGE}/cv-information`
export const BUCKET_IMAGE_CV_INFORMATION_UPLOAD= `images/cv-information`
export const BUCKET_IMAGE_COMPANIES = `${BUCKET_IMAGE}/companies`
export const BUCKET_IMAGE_COMPANIES_UPLOAD = `images/companies`
